AOM_CHECK_MEM_ERROR: add an assert for a valid jmp target
callers of AOM_CHECK_MEM_ERROR() expect failures to not return

Bug: aomedia:3276
Change-Id: I0adf0320c801a580f0f2de12557e0534d6d91606